

spring:
  datasource:
    url: jdbc:mysql://120.79.141.204:3306/security?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    logSlowSql: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    #useGlobalDataSourceStat: true

  #mybatisplus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.each.bookserver.entity
  global-config:
    db-config:
      id-type: AUTO
      field-strategy: NOT_EMPTY
      db-type: mysql
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:    #--log4j
  config: classpath:log4j2-spring.xml
  level:
    com.each.mybatisplus : trace


jwt:
  tokenHeader: Authorization
  secret: each
  #  是否设置token过期
  expired: true
  #  过期时间，毫秒
  expiration: 600000
  head: "Bearer "
  #  不需要token认证和跳过security认证的URI,支持*通配符，必须以 / 开头
  permitUris: "/register,/,/favicon.ico,/api/logManage/info/export,/download,/export,/api/product/exportAllDate,/produce/test,/testapi/**,/api/deviceOS/getDeviceOutputStatistics,/api/**,/export/**,/warehouseTest/**"
